version: "3"

silent: true
dotenv: ['.env']
tasks:
  d:up:
    desc: Startup docker containers
    cmds:
      - ./vendor/bin/sail up -d
  d:down:
    desc: Shutdown docker containers
    cmds:
      - ./vendor/bin/sail down
  d:build:
    desc: (re)-build Docker image
    cmds:
      - docker build . --no-cache
  w:prep:
    desc: Prepare dev environment (composer install, npm run, etc.)
    cmds:
      - ./composer.phar install
      - npm install
      - npm run dev
  w:db:migrate:
    desc: Run pending migrations
    cmds:
      - docker exec -it app php artisan migrate
  w:db:reset:
    desc: Reset database
    cmds:
      - docker exec -it app php artisan migrate:fresh
      - docker exec -it app php artisan db:seed
  d:sql:
    desc: Get into sql console
    cmds:
      - docker exec -it db mysql -u $DB_USERNAME --password=$DB_PASSWORD $DB_DATABASE
