<?php

namespace App\Http\Controllers;

use App\Models\Coupon;
use Illuminate\Http\Request;
use Illuminate\View\View;

class CouponController extends Controller
{
    public function index()
    {
        return view('admin.coupons', ['coupons' => Coupon::all()]); // TODO: Change the autogenerated stub
    }

    public function delete()
    {

    }

    public function create()
    {

    }

    public function edit()
    {

    }

    private function mapValues()
    {

    }
}
